### ISSUE TITLE
Internal Error: Contact Admin

### ISSUE THREAD

**Issue by tonytonyistony** [LibreSign/libresign#1300]
I have the app installed and all add ins marked as OK. I have granted every user on the server access to LibreSign. When a user attempts to sign a document and enter their password, I get an error stated "Internal Error: Contact Admin". The details in the nextcloud.log are pretty bland.

{
  "reqId": "Puza8XLp4BrTGOnucqed",
  "level": 3,
  "time": "December 20, 2022 07:10:34",
  "remoteAddr": "10.133.1.201",
  "user": "tony.****",
  "app": "libresign",
  "method": "POST",
  "url": "/apps/libresign/api/0.1/sign/uuid/d14b9f70-60c2-4432-b73a-393b48d2f666",
  "message": "Error to sign PDF. [\"sh: 1: : Permission denied\"]",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
  "version": "24.0.6.1",
  "data": {
    "app": "libresign"
  }
}

Im not sure what permission Im needing to allow at this point to get it to work. Any help would be appreciated.

**Comment by vitormattos** [comment]
Did you verified the LibreSign setup on Administration settings > LibreSign and is all ok?

This error is a bit strange because haven't the backtrace.

Other point is that we stopped the updates of LibreSign compatible with Nextcloud 24 because we haven't founders or a company paying to do this.

I will close this issue because is about a no more supported version.

If you want to use the newest version of LibreSign with community support, I recommend  to migrate to Nextcloud 25.

**Comment by tonytonyistony** [comment]
Thanks for the quick reply. I'll get my nextcloud updated and see if that changes the behavior. I'll repost with more info next time if it still doesn't work.
