### ISSUE TITLE
Internal Error Contact Admin

### ISSUE THREAD

**Issue by kennganga** [LibreSign/libresign#1414]
Hi have installed NC on ubuntu 22.04 and installed the libresign app.I have added a user to the allowed to sign and configured the signature and initials. However on requesting a signature the user gets an email and opens the pdf but on clicking sign document the user enters the password and gets an error Internal Error Contact Admin.

Kindly assist.

**Comment by lhsazevedo** [comment]
Hi, @kennganga. Could you try in the latest release (6.2.6)?
Note that this release is compatible with Nextcloud 25 only. We do not support previous versions anymore, as we haven't sufficient funding at the moment.

**Comment by kennganga** [comment]
Hi Lucas,
Thank you very much for your assistance.I managed to upgrade to NC 25 and
installed the libresign. Now I can sign documents but have one question is
it supposed to insert the visible signature on the document I can see the
status that the document is signed but on opening the pdf cant see it. Or
would you be kind and share on the steps on how it works seems to be
missing the manual on that or how it works. Thank you for your time.

**Comment by vitormattos** [comment]
Hi @kennganga,

You need to open the signed document at an editor that can read digital signatures, by example https://okular.kde.org/

If you want to put a visible signature, you need to answer that you want to do this when you send a file to sign from app Files or clicking to add visible signatures at details tab of a document inside the LibeSign app.

To implement improvements on LibreSign we need more funding. If you or your company want to integrate the LibreSign with other softwares or change anything at the flow, tell us about your necessity and we will do the best to help you.

If isn't a company, you will need to send your feature request at this repository and wait by a developer from community that want to implement the feature for free.

closing this issue because isn't a problem of newest version.
