### ISSUE TITLE
Access REST API

### ISSUE THREAD

**Issue by feefladder** [LibreSign/libresign#1486]
**Describe the bug**

How to access the API? if I go to https://nextcoud.xxx.eu/index.php/libresign/api/v1.0, it just redirects me to `/apps/dashboard/`. How can I access the API interface as is visible on https://libresign.github.io/api/ ?

**To Reproduce**
- I'm an authenticated user
- Go to '/index.php/libresign/api/v1.0'
- See error

**Expected behavior**
To be directed to this API page

**Screenshots**

**Environment information (please complete the following information):**
 - OS: Docker
 - Browser FireFox
 - LibreSign Version 6.2.8
 - [Nextcloud Hub 3](https://nextcloud.com/) (25.0.3)
 - Logs no admin access

**Additional context**

**Comment by vitormattos** [comment]
You need to do a request to a specific endpoint that you can see here: https://libresign.github.io/api/

If you do a request to the root path of API, will be an invalid URL and you will be redirect to dashboard.

This isn't a bug, this is the expected behavior.

You also can check this link with examples about how to do a request to the API:
https://libresign.github.io/Getting-started.html

**Comment by feefladder** [comment]
@vitormattos So just to make ik clear, this api interface on your pages is impossible to get on my nextcloud instance to try things out?

Thanks for your quick helpful answer :)
