### ISSUE TITLE
Custom default user folder doesn't work

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#1585]
Libresign 6.3.0

I setup the custom default user folder to .LibreSign (so it will be a hidden folder), create a signature and it's created under LiberSign (regular folder).

Expected behavior: the cert should be created under .LibreSign as hidden folder.

**Comment by vitormattos** [comment]
Check the folder setting:
```bash
occ user:setting admin libresign folder
```

I didn't changed the previous values by security to don't broke if the user already have a folder with files. If you change the folder and the user have a folder, all references at libresign tables will broke.

This setting only will work to users that didn't created the LibreSign folder. To user that already have the folder, take care and run the follow command to delete the setting to each user that already have the LibreSign folder:

```bash
occ user:setting --delete admin libresign folder
```

When the users do anything that need to recreate the folder, will use the new value because haven't the old value.
