### ISSUE TITLE
What eIDAS signature level would Libresign be considered as ?

### ISSUE THREAD

**Issue by odobrev** [LibreSign/libresign#1788]
Hello there from France.

We are a small electricity network operator in France that have been using Owncloud since 2016 and switched to Nextcloud since late 2019.

We are quite interested in self hosted open source solutions like Libresign which I think could be a really great solution for small compagnies like ours to implement a valid signature solution that keeps our files where they need to stay and that is behind our firewall and not in some shady cloud which access could be revoked at any time by the service provider.

Libresign is not perfect but could be enough as it is right now to anwser to many of our needs in terms of document signing.

The only thing that is bothering me is that I can't manage to identify where the solution is situated in eIDAS regulations. (https://www.ssi.gouv.fr/entreprise/reglementation/confiance-numerique/le-reglement-eidas/)
I'm sorry I didn't manage to find english documents but I hope that google translate could help you read the contents if you need more.

The French government have issued a post on it's website dedicated to digital transformation : https://www.francenum.gouv.fr/guides-et-conseils/pilotage-de-lentreprise/dematerialisation-des-documents/la-signature
Which clearly defines 4 levels of signature :
Level 1 =>  Simple Electronic Signature (SES) : a basic scan of a manual signature for example or a picture of your signature insterted through Adobe or any other PDF signature tool that has this basic function included.
Level 2 => Advanced Electronic Signature (AES) : this one implements a clear process to identify the user and give it full control over it's identification data. It also guaranties document intergity after signing and can detect any changes made to the document after it's signing.
Level 3 => Advanced Electronic Signature with Qualified Certificate (AES + Qualified Certificate) : Same process as AES but with a proper certificate delivered by a qualified eTrust provider using specific identification process.
Level 4 => Qualified Electronic Signature (QES) : Same process as Level 3 but you also need a specific Cryptographic Device.

We are already working with Certeurope which provides Digicert / Quovadis certificates.
We do have a QES device for some specific use cases but as I understand, Libresign is not (yet ?) meant to be able to handle these kind of devices so Level 4 is out of question righ now.

I feel like from scratch, Libresign (using self signed CA and user pfx certificates) would still be considered as Level 1 SES signature.

You would need to buy at least RGS* certificate per user and replace pfx file directly in user directory to switcch to Level 2 AES.

But what about level 3 ? Certeurope seems to be able to deliver RGS** qualified certificates.
Do you think that using it directly in Libresign user directory instead of self-signed ones would be enough to qualify the whole process as Level 3 ?

Sorry for this big text block and my poor English, but I feel like since Libresign really has a great potential and I think I'm not the only one that would want to know where are the limits right now of this solution and since I didn't see any place talking about this information.

Greetings.

**Comment by odobrev** [comment]
I found a tool online that could help with validation : https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/validation
It seems to be picky though.
(You don't need to put both files in fields, second field is optional).

**Comment by vitormattos** [comment]
Level 1 => Simple Electronic Signature (SES) : a basic scan of a manual signature for example or a picture of your signature insterted through Adobe or any other PDF signature tool that has this basic function included.

LibreSign don't do this because use the pattern PKCS#7 and sign using a pattern that ist possible identify if the document, after signed, wasn't changed and if the signers is really the signers.

Level 2 => Advanced Electronic Signature (AES) : this one implements a clear process to identify the user and give it full control over it's identification data. It also guaranties document intergity after signing and can detect any changes made to the document after it's signing.

All PKCS#7 is an AES, but not all AES is PKCS#7. LibreSign implement PKCS#7. With LibreSign is possible create a Certificate Authority inside your own instance with CFSSL and at the next LibreSign version also with OpenSSL to generate the PFX files.

Level 3 => Advanced Electronic Signature with Qualified Certificate (AES + Qualified Certificate) : Same process as AES but with a proper certificate delivered by a qualified eTrust provider using specific identification process.

When whe have a Qualified Certificate is when the Certificate Authority is under the government root Certificate Authority. This occur when the PFX files is generated by a CA under this organization. Using the root certificate of LibreSign, don't will generate a qualified certificate, but is possible to use your generated qualified certificate inside LibreSign replacing the pfx file by your pfx file generated by another certificate authority. 

You received the information that you sent here because the certificate chain isn't under the government. If you have your own pfx file you can put inside LibreSign, sign the document and get green at all return on this page.

Level 4 => Qualified Electronic Signature (QES) : Same process as Level 3 but you also need a specific Cryptographic Device.

To do this is necessary to use a physical token, like a FIDO or like the eIDAS physical card that you need to put into a card reader to sign the document. At this moment LibreSign haven't support to sign using physical cards but we want to implement this. Now we need funding to be possible dedicate paid time to implement this way of signing.

**Comment by tasagore** [comment]
...and at the next LibreSign version also with OpenSSL to generate the PFX files....

Any chance to know the new features and ETA of the new version?

And off-topic but...the main problem of this tool (for me) is that doesn't work in mobile devices, do you have any plan to fix that feature?

**Comment by vitormattos** [comment]
Hi people!

I created a new release with the feature to upload your own certificate. Could you test the new release?

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
