### ISSUE TITLE
LibreSign future?

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#1959]
Hi, not a bug, not a request feature, just a doubt about the future of the project.

I see some post suggesting a "Major release 28", don't know if it means that this project is going to be part of the NC28 package or if it means that the next LibreSign release will be after NC28 presentation, if there is going to be any release before that...

Also may be a enterprise version should be fine for most of us (I guess that without funds this can not be upgraded as it needs).

Regards

**Comment by vitormattos** [comment]
Hi, very happy for your message and interest in the future of the project! 😃

Today we do not have funding to maintain the project and we have been working voluntarily to keep development active until the project becomes financially sustainable, making it possible to expand the team, improve quality and speed up development.

Regarding version 28, our hope is that along with the launch of Nextcloud 28, scheduled for mid-December, we will be able to conclude with the next version of LibreSign to launch it at the same time as Nextcloud 28.

As there is no funding to maintain backwards compatibility, we have currently decided to continue development only for version 28 of Nextcloud.

The next version of LibreSign has a lot of code rewriting, both on the API side and on the frontend. Among many improvements, the one that will be most relevant in my opinion is to enable different methods of identifying who must sign the documents. This will make it possible, for example, for the administrator to define globally whether it will be possible to request a signature from a person who has a Nextcloud account, email, cell phone or some other method of identification.

It is my greatest hope that the project will obtain financing. I have a lot of affection for this particular project which is, as far as I know, the only digital signer in the 100% open source PKI standard.

As a member of the community, if you know or have ways to support the project, you can inform us at contact@librecode.coop or via GitHub Sponsor https://github.com/sponsors/LibreSign

**Comment by zebfns** [comment]
Just curious, what kind of financing would be necessary to get this working for NC 27 & 28?

**Comment by vitormattos** [comment]
At the current release of LibreSign I started to do a lot of improvements to be possible implement the feature that I called as "multiple identify factors of a signer" and I started to tho this at this very big PR:
- https://github.com/LibreSign/libresign/pull/1658

I follow stabilizing the code after this PR to launch the next release that started in April, during the cycle of Nextcloud server 27.

In the most of time, because we (the LibreSign community) don't have anyone helping to funding this project, I work alone using my volunteer time and I didn't get able time to do all the necessary changes to launch the release compatible with Nextcloud server 27 and do the work to maintain the code-base up-to-date and compatible with next versions of Nextcloud server (now will be 28 at 12th December).

I love a lot to work at this project and I wish to follow doing this maintaining as open source project, but I need help to pay my bills and also to put other developers working together with me because a project maintained only by a developer it's not healthy to the project. This isn't a small project and is important to have other engineers working together with me and don't jump again another major version of Nextcloud Server ignoring the previous version.

To create a stable version compatible with Nextcloud 27 will be necessary port the code-base to work with this version and make all necessary tests to be stable. This will be a big work and maybe, at this moment, since the zero money to pay the bills, maybe will be best only go ahead with the next version.

Resuming, to be possible will be necessary at least of a new engineer. I think that, at this moment, 3 engineers would be enough to we have a good team working in the core of this project making this a stable and beautiful open source project. Now is only me and to have more engineers, we will need funding to pay the bills of new engineers.

I'm open to help. How you knewed the project and what you want or what you need or if you have questions about how to help the project?

**Comment by zebfns** [comment]
We are a small law firm that is very interested in using open source for all of our core needs. We are open to helping fund this project because we believe it has great potential.

We had it running under NC 26 for testing and it worked well. There were a few features I felt needed to be implemented before relying on it full-time. The big one is the ability to remove documents if they no longer need to be signed.

Unfortunately we are not in the position to fund full time development staff but we could potentially offer a bounty for specific features or improvements.

We could wait until we upgrade to NC 28 to implement LibreSign of course, but being able to deploy on our current 27 server would be fantastic.

If you were to put a price tag on making it compatible with NC 27, what is your estimate?

Thank you for the quick reply and thank you for your work on this important project.

**Comment by vitormattos** [comment]
I'm very happy to know that the project is helping to your business. Commonly I can't know how much people are using this project because is totally open and haven't a tracking.

Don't boring talking about code, to be more precise about an estimate to make compatible with 27, will be necessary rewrite a bit the integration with app Files (the menu at PDF file) and fix the possible problems at API side. I will check and return here with a more objective answer to you.

About the upgrade, of your setup, if you wish, I also can do a consulting to help you or the sysadmin of your company or also doing the necessary to migrate your environment to newest version of server.

And I thanks a lot by your quick reply too!

**Comment by vitormattos** [comment]
Hi @tasagore 

About the next version that will be compatible with Nextcloud 28

1. Fixed and will come in the next version
2. Done and will come in the next version
3. Partial added at 28 because now is possible collect all metadata but haven't an interface to list the log.
4. I have not plans to implement this to next release, but I wish to do this maybe during the cicle of 28 version. I think that a WYSIWYG editor with system tags (i.e `{qrcode}`) could solve this.

Sounds that helping to funding issues would be a good idea. Did you have a suggestion about a platform to funding issues? A very popular platform is Bountysource but have important questions about [here](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).  Exist other platforms like this but I'm not familiar. Also is possible to use [GitHub Sponsors](https://github.com/sponsors/LibreSign) of LibreSign project.

**Comment by vitormattos** [comment]
Now we have two new releases compatible with Nextcloud 28 and 29

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop
