### ISSUE TITLE
Nextcloud 28.0.2 Libresign gives internal server error when click on View

### ISSUE THREAD

**Issue by dolphinscorp** [LibreSign/libresign#2284]
**Describe the bug**
Unable to view signed document when clicked on signed document following error occur
![image](https://github.com/LibreSign/libresign/assets/115947558/ab0d290a-78d3-45af-91ac-ea9c67d04cc8)

**To Reproduce**
Click on signed document and then click on view

**Expected behavior**
Signed docuement should open

**Environment information (please complete the following information):**
 - OS:Debain 12
 - LibreSign Version [e.g. 3.2.1]
 - Nextcloud Server: 28.02
 - Logs:
 [index] Error: Call to undefined method OCP\AppFramework\Http\ContentSecurityPolicy::allowInlineScript() in file '/var/www/html/nextcloud/files/apps/libresign/lib/Controller/PageController.php' line 136
	GET /index.php/apps/libresign/p/pdf/f75c74df-bf14-45c6-9c82-25d121da81db?_t=1707748452358
	from 172.232.44.191 by zohaibs at Feb 12, 2024, 7:34:12 PM

**Comment by dolphinscorp** [comment]
Also trying to upload pdf but it gives following error

![image](https://github.com/LibreSign/libresign/assets/115947558/0c3e9fa3-6a4d-4e03-a8aa-cf2e56c9d737)

**Comment by vitormattos** [comment]
Closing this issue because if about an old version of LibreSign.

Please use the latest release compatible with Nexcloud 28.

**Comment by dolphinscorp** [comment]
Hi

This new version Libresign is not yet available in nextcloud store?

**
![image](https://github.com/LibreSign/libresign/assets/115947558/a3b86c37-bf2f-403e-b853-394d754d6576)

**

Maximum available version is 7.1.1 in my nextcloud app store?

@vitormattos

**Comment by vitormattos** [comment]
Yes, isn't visible at appstore yet.
To appstore this is classified as nightly build, is a release candidate.
This version could have bugs and because this I will wait more to create a stable release. Only stable releases is possible to install from appstore.
I recommend to use this version only in a test environment because to make a rollback isn't easy (is necessary touch handmade the tables).
For now, you can test this release candidate removing your current libresign folder inside your app folder by content of .tar.gz file of release candidate file.
