### ISSUE TITLE
"Open in LibreSign" option not visible in Files menus

### ISSUE THREAD

**Issue by DazeEnd** [LibreSign/libresign#2778]
**Describe the bug**
In the Files app, when the details pane is open and width of the browser viewport is relatively narrow, the "Open in LibreSign" option does not appear when you right-click on a file, or when you click the ellipsis ("...") button. It is outside the visible frame of the menu, and you have to scroll to find it. There is no visual indication that the menu can be scrolled, so it is difficult to discover.

**To Reproduce**
1. Log into Nextcloud and open the Files app.
2. Adjust the size of the browser window so that the width of the browser viewport is between 1084 pixels and 1484 pixels.
3. Right-click on a file, and examine the menu that appears.
4. Click on the ellipsis ("...") button next to a file and examine the menu that appears.
5. Right-click on a file, and select "Open Details" to open the details pane.
6. Right-click on a file, and examine the menu that appears.
7. Click on the ellipsis ("...") button next to a file and examine the menu that appears.

**Expected behavior**
In steps 3, 4, 6, and 7, an "Open in LibreSign" option should appear in all the menus that are displayed.

**Actual behavior**
In steps 3 and 4, the "Open in LibreSign" menu option appears as expected.

In steps 6 and 7, the "Open in LibreSign" menu option does not appear unless you scroll down on the menu.

**Screenshots**
Results from Step 3:
![Screenshot from 2024-04-16 10-17-55](https://github.com/LibreSign/libresign/assets/2699247/cf9f5489-0046-4523-ae96-22a7d0b9175a)

Results from Step 4:
![Screenshot from 2024-04-16 10-18-08](https://github.com/LibreSign/libresign/assets/2699247/5946dc52-98e1-425b-946f-fba7243c8c2e)

Results from Step 6:
![Screenshot from 2024-04-16 10-19-30](https://github.com/LibreSign/libresign/assets/2699247/d0ff6632-734d-46cc-af7e-6f2c6ee71f67)

Results from Step 7:
![Screenshot from 2024-04-16 10-20-04](https://github.com/LibreSign/libresign/assets/2699247/bf0f5a49-385a-405a-ae54-a992249a98d8)

Video showing scrolling the menu:
[Screencast from 2024-04-16 10-22-18.webm](https://github.com/LibreSign/libresign/assets/2699247/67679350-b561-4d85-9322-a70deeed08d2)

**Environment information (please complete the following information):**
 - Server OS: AlmaLinux 8.4
 - Browser: Firefox
 - LibreSign Version: v8.0.0-rc11
 - Nextcloud Server Version: 28.0.4
 - Logs: N/A

**Additional context**
This problem seems to be connected to the display of the "Show sharing options" button (![Screenshot from 2024-04-16 10-33-40](https://github.com/LibreSign/libresign/assets/2699247/e20c46e7-7c23-46cf-90b2-1a8a7b71a439)) on a file's row. When the "Show sharing options" button is displayed, then the problem does not appear. When the width of the browser window is adjusted so that the "Show sharing options" button disappears (and the option is moved to the menu), then the problem appears.

**Comment by vitormattos** [comment]
This is a problem about Nextcloud files. The items of menu is ordered by a property called [order](https://nextcloud-libraries.github.io/nextcloud-files/classes/FileAction.html#order), is a numeric property that all apps define the value that want to use, could be positive and negative values, most negative values will come in begin of list. The order value of LibreSign is [100](https://github.com/LibreSign/libresign/blob/020539a13e7fe0f3107f2b95bac6877bd7650ec5/src/actions/openInLibreSignAction.js#L51).

To have a best understanding about the order values used, I made a search at my development environment and found the data of follow table.

Looking the table I think that we can choose a different value. The problem is that the value is a bit "random" and depend of order values defined by other apps installed that have FileActions.

Did you have any suggestion about a best order value?

| app             | file                                        | location | order |
| :-------------- | :------------------------------------------ | :------- | :---- |
| files_sharing   | src/actions/openInFilesAction.ts            | 53,2     | -1000 |
| files_external  | src/actions/openInFilesAction.ts            | 71,2     | -1000 |
| files_sharing   | src/actions/openInFilesAction.ts            | 51,2     | -1000 |
| comments        | src/actions/inlineUnreadCommentsAction.ts   | 62,2     | -140  |
| files           | src/actions/openFolderAction.ts             | 66,2     | -100  |
| files           | src/actions/favoriteAction.ts               | 103,2    | -50   |
| files           | src/actions/sidebarAction.ts                | 74,2     | -50   |
| files_reminders | src/actions/reminderStatusAction.ts         | 61,2     | -15   |
| approval        | src/files/actions/inlineAction.js           | 45,2     | -10   |
| approval        | src/files/actions/inlineAction.js           | 45,2     | -10   |
| approval        | src/files/actions/approveAction.js          | 19,2     | 0     |
| approval        | src/files/actions/rejectAction.js           | 19,2     | 0     |
| approval        | src/files/actions/rejectAction.js           | 19,2     | 0     |
| systemtags      | src/actions/inlineSystemTagsAction.ts       | 104,2    | 0     |
| approval        | src/files/actions/requestAction.js          | 21,2     | 1     |
| files_trashbin  | src/actions/restoreAction.ts                | 76,2     | 1     |
| files_sharing   | src/actions/acceptShareAction.ts            | 61,2     | 1     |
| files_src       | sctions/moveOrCopyAction.ts                 | 336,2    | 15    |
| files_reminders | src/actions/clearReminderAction.ts          | 70,2     | 19    |
| files_reminders | src/actions/setReminderMenuAction.ts        | 39,2     | 20    |
| files_reminders | src/actions/setReminderSuggestionActions.ts | 120,3    | 21    |
| files_reminders | src/actions/setReminderCustomAction.ts      | 44,2     | 22    |
| files           | src/actions/editLocallyAction.ts            | 67,2     | 25    |
| files_src       | sctions/downloadAction.ts                   | 101,2    | 30    |
| files           | src/actions/viewInFolderAction.ts           | 70,2     | 80    |
| libresign       | src/actions/openInLibreSignAction.js        | 51,2     | 100   |

**Comment by DazeEnd** [comment]
It sounds like this is a Files bug related to Files not properly resizing its menu, rather than a LibreSign issue. I think the order=100 value you chose is probably appropriate. And frankly, if something had to get bumped off that menu, it should probably be LibreSign. I will consider filing this bug against Files, and you can close this issue if you want.

**Comment by vitormattos** [comment]
This problem also occur at Administration Settings side. The items that you can see at Administration Settings section is ordered by an order number defined by developers.

I made the same search looking by order value of all apps that appear at Administration Settings.

Maybe a possible suggestion to Nextcloud team is to implement a tool to be possible choose the order that the apps will appear at Administration Settings and at `FileActions`. Maybe a good implementaito to this would be:
Order Administration Settings apps by:
* Alphabetic
  * Asc
  * Desc
* Original order
* Custom order
  * Show a list of apps and allow to order herself

Follow the list of apps at Administration Settings at my developer environment:

| app                    | path                   | location (row and column) | order |
| :--------------------- | :--------------------- | :------------------------ | :---- |
| guests                 | lib/Settings/Admin.php | 53,3                      | 0     |
| richdocuments          | lib/Settings/Admin.php | 111,3                     | 0     |
| richdocumentscode      | lib/Settings/Admin.php | 75,9                      | 0     |
| approval               | lib/Settings/Admin.php | 29,3                      | 1     |
| theming                | lib/Settings/Admin.php | 113,3                     | 5     |
| user_ldap              | lib/Settings/Admin.php | 99,3                      | 5     |
| encryption             | lib/Settings/Admin.php | 100,3                     | 11    |
| updatenotification     | lib/Settings/Admin.php | 161,3                     | 11    |
| federatedfilesharing   | lib/Settings/Admin.php | 92,3                      | 20    |
| notifications          | lib/Settings/Admin.php | 99,3                      | 20    |
| federation             | lib/Settings/Admin.php | 65,3                      | 30    |
| files_external         | lib/Settings/Admin.php | 93,3                      | 40    |
| sharebymail            | lib/Settings/Admin.php | 67,3                      | 40    |
| breezedark             | lib/Settings/Admin.php | 87,9                      | 50    |
| activity               | lib/Settings/Admin.php | 129,3                     | 55    |
| announcementcenter     | lib/Settings/Admin.php | 71,3                      | 55    |
| external               | lib/Settings/Admin.php | 62,3                      | 55    |
| systemtags             | lib/Settings/Admin.php | 54,3                      | 70    |
| side_menu              | lib/Settings/Admin.php | 208,9                     | 70    |
| files_automatedtagging | lib/Settings/Admin.php | 58,3                      | 75    |
| logreader              | lib/Settings/Admin.php | 66,3                      | 90    |
| groupfolders           | lib/Settings/Admin.php | 79,3                      | 90    |
| oauth2                 | lib/Settings/Admin.php | 82,3                      | 100   |
| libresign              | lib/Settings/Admin.php | 72,3                      | 100   |
| terms_of_service       | lib/Settings/Admin.php | 50,3                      | 100   |

**Comment by vitormattos** [comment]
Have two places to registry this problem and would be good to you create and not me and also would be good to use other app as example.

The menu of app Files is managed by this repository:
https://github.com/nextcloud-libraries/nextcloud-files/
https://github.com/search?q=repo%3Anextcloud-libraries%2Fnextcloud-files%20order&type=code

The menu at Administration Settings is generated by this repository:
https://github.com/nextcloud/server/blob/master/lib/private/Settings/Manager.php#L258

LibreSign for now haven't Personal Settings at Nextcloud menu (but I think that could be a good idea to have). The Personal settings menu also have the same way to order.

I made a search at both repositories but I didn't found any issue related to this. I think that would be good to create a new issue.

Looking a bit the Nextcloud code about Administration Settings, I found that is provided by a class called `FilteredSettingsManager` and I think that we can override this and implement an app to implement custom sort to itens under Administration Settings. But would be very nice to this be a native option, implemented at server side.

And about `FileActions`, sounds that will be very complex to implement this as a new app side to manage the order because the implementation at frontend haven't hooks or events to make possible change the order of menu. To do this from a new app side will be necessary implement a new menu logic, this is a way that will impact all apps. To do this will be necessary to implement this at Nextcloud side.

**Comment by vitormattos** [comment]
I will change the order value to 1. What you think about @DazeEnd ?
At Nextcloud side only was made adjust to show a biggest scrollbar.

**Comment by vitormattos** [comment]
Thinking more, maybe would be best use -1000 to be at the top of this menu because LibreSign only will appear at this menu when is a PDF file.

**Comment by DazeEnd** [comment]
I like the idea of making LibreSign the first option, but only on PDF files.

By the way, my issue was closed as "not planned". Apparently they are adding more obvious scroll bars, which they think will alleviate the problem.

**Comment by vitormattos** [comment]
Yes, the LibreSign item only appear at menu when the mime-type is `application/pdf`
