### ISSUE TITLE
Libre Sign password recover

### ISSUE THREAD

**Issue by anzal-ahmed** [LibreSign/libresign#3474]
How to recover libre sign password as a next cloud admin for a user who dont remember his old password?

**Comment by vitormattos** [comment]
The LibreSign password can't be recovered because is necessary to have the current password to decode the PFX file and encode with a new password.

If is a certificate generated by LibreSign, you can delete the current certificate and create a new certificate. You can do this at LibreSign.

You can do this at this point:

![Screenshot_20240729_101643](https://github.com/user-attachments/assets/894770c8-b523-4ab5-a998-8931f493fec5)

Or also at the signature page on "fortot password"

![Screenshot_20240729_101844](https://github.com/user-attachments/assets/72d224ba-86a2-42b9-98bb-8f112453b0d4)

![Screenshot_20240729_101937](https://github.com/user-attachments/assets/af706a47-f6e5-4a8e-9f82-4a770c44f7b8)

We need help to funding this project. If LibreSign is an important app to your business, you can help us by a recurrent or unique GitHub sponsor:

- https://github.com/sponsors/LibreSign

**Comment by dolphinscorp** [comment]
Is it possible to recover it from DataBase?

**Comment by vitormattos** [comment]
This issue already was closed.
To new questions, open a new issue.
