### ISSUE TITLE
unable to access signature URL

### ISSUE THREAD

**Issue by c00ntact** [LibreSign/libresign#387]
Can I please ask for some help in figuring out why I am unable to access the file signature URL in the notification email.
I believe that I have everything working cfssl is working and I have configured libresign.
I am able to request files to be signed and as long as I am logged in as that user I am able to sign the documents in the LibreSign app.
What I am currently trying to figure out is how to access the URL that is shared with the user via email.
Once I click on the sign <XYZ> document button on the email I get redirected to https://<server name>/nextcloud/index.php/apps/libresign/sign/<UUID>/error
I get a 404 error message stating that "This is not your file"
I looked in the web root folder under /nextcloud/app/libresign/ and did no see a "sign" folder which I thought might be generated dynamically.

Can you please help me how to troubleshoot this. Thank youy

**Comment by vitormattos** [comment]
To access a URL received by e-mail, you must not have an active Nextcloud session in the browser that accesses the URL, otherwise LibreSign will believe that the link belongs to the authenticated user and it is not, it is from another user.

You will only be able to access the link you received via email while having an active session in the browser if the email was sent to the same email address as the authenticated user.

If the person who receives the email does not have an account on Nextcloud, they will see the account creation screen, on this screen they MUST use the same email address as the invitation to create an account.

**Comment by wesleyguirra** [comment]
Same as above

**Comment by c00ntact** [comment]
My issue was caused by using an old JSignPdf version ... after upgrading to JSignPdf-1.6.5.zip everything worked perfectly. Thank you

**Comment by vitormattos** [comment]
There is a setting to define the path of jSignPDF. For now it can only be changed by occ:
```
occ config:app:set --value <rootpathhere> libsign jsignpdf_jar_path
```

**Comment by futurewebpn** [comment]
just wondering, could it also be signed "without" the user need to create an account?

**Comment by joedust** [comment]
> just wondering, could it also be signed "without" the user need to create an account?

yeah, what about that? would be awesome killer feature...
