### ISSUE TITLE
Validation page with apache web server

### ISSUE THREAD

**Issue by upultfs** [LibreSign/libresign#457]
Can someone help me to find the apache directives validation page? In Libresign setup documentation Nginx configuration there but I'm using an apache web server.

**Comment by vitormattos** [comment]
You can use the default URL to do this. In example:

http://localhost/apps/libresign/validation/

On this version if the URL will can big and maybe can't have space to put on footer of the page, because this, a solution is creating a redirection from a small route with the UUID to the full path. We fixed this on main branch but we need stabilize the code to launch a new release.

You can help the project contributing montly as a patron on Patreon or asking me directly by other ways to contributing to funding the project. We need  more software engineers working on this project to implement new features and improvements.

**Comment by upultfs** [comment]
@vitormattos  Yes, I can help to develop new features.

**Comment by DaianeAlvesRJ** [comment]
Hi @uultfs do you still want to support the LibreSign project to develop new features?

**Comment by DaianeAlvesRJ** [comment]
Hi, @upultfs.
Do you still want to support the LibreSign project to develop new features?

**Comment by sollermun** [comment]
Did anyone figure out this issue? I am unable to set up a Validation URL using Apache. Everything redirects to the request signature page.

**Comment by vitormattos** [comment]
LibreSign was updated, check if the problem persist in latest version.

I recommend to use with server in version 25.

If the problem persists, reopen this issue with more details.
