### ISSUE TITLE
Cannot Sign the Document

### ISSUE THREAD

**Issue by nvlrdn** [LibreSign/libresign#834]
I tried to sign a document using libresign, and unfortunately when I signed the document there was an error like "Document not available for signature" I've tried to uninstall and reinstall libresign but the error still occurs

**Comment by tasagore** [comment]
Same here. I've installed a standalone instance in a NC 24, uploaded a document, signed it and all was ok. Tryed a second one and..."Document not available for signature", don't know why but I've been able to sign just the first one, no more.

No errors in apache or nextcloud log.

**Comment by vitormattos** [comment]
This message is send when the document don't was sent to sign.
Verify if you put visible signatures, saved the place of visible signature, and you send the document to sign.
This message is returned when the status of the document isn't able to sign, isn't a bug.

**Comment by tasagore** [comment]
> This message is send when the document don't was sent to sign.
> Verify if you put visible signatures, saved the place of visible signature, and you send the document to sign.
> This message is returned when the status of the document isn't able to sign, isn't a bug.

I didn't setup "visible signatures", in fact I don't know where to setup that.

I installed libresign, signed first document, all was ok, after that was not able to sign anymore because the message appears, no matters if I try with a new user or a old one, can't sign anything.

Anyway I still consider this a bug (mixed with feature request) because If the problem is the "visible signature" enabled (altought I guess this is not the case) and the user does not have one the message should be "you need to setup your signature before signing" and a link to do that (or something like that), in fact when a user sign for first time a password is mandatory and works in that way, this should be the same.

**Comment by tasagore** [comment]
I guess the problem is about visible signatures, the bug is that the email should not be sent if the document is in draft mode (see https://github.com/LibreSign/libresign/issues/886#issue-1334523584) because it's not ready for signing.
